In [1]:
#載入 Numpy 模組
import numpy as np
print("一、建立一個8x8的列表【元素皆為1】")
z = np.ones((8,8))
print (z)

一、建立一個8x8的列表【元素皆為1】
[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


In [2]:
print("二、建立一個8x8的列表【元素皆為0】")
z = np.zeros((8,8),dtype=int)
print (z)

二、建立一個8x8的列表【元素皆為0】
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


In [3]:
# z [開始位置::距離下一列的距離]
#z[1::4] 第1列都為1    下一列(1+4=5)皆為1  
#  列     行
# 1::2 , ::2

print("三、第1列(含)每隔兩列 & 第0行(含)每隔兩行 =1 ")
z[1::2,::2] = 1
print (z)

三、第1列(含)每隔兩列 & 第0行(含)每隔兩行 =1 
[[0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]]


In [4]:
print("四、第0列(含)每隔兩列 & 第1行每隔兩行 =1 ")
z[::2,1::2] = 1
print (z)

四、第0列(含)每隔兩列 & 第1行每隔兩行 =1 
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [5]:
print("五、隨機建立5x5列表元素0~1之間")
x = np.random.random((5,5))
print(x)

五、隨機建立5x5列表元素0~1之間
[[0.30065736 0.89269421 0.2748534  0.05365058 0.6584911 ]
 [0.2011469  0.92340711 0.06546844 0.44974785 0.76010712]
 [0.93787381 0.6547456  0.13551976 0.96293849 0.35750707]
 [0.37476376 0.23233572 0.03476721 0.97478001 0.03414822]
 [0.07507676 0.58384428 0.59400963 0.7781294  0.71076678]]


In [7]:
print("六、列印出x列表中最小值")
x1 = x.min()
print("min",x1)

六、列印出x列表中最小值
min 0.03414821649363875


In [8]:
print("七、列印出X列表中最大值")
x2 = x.max()
print("max",x2)

七、列印出X列表中最大值
max 0.9747800099794455


In [9]:
print("八、列印最大值及最小值")
x3,x4=x.min(),x.max()
print(x3,x4)

八、列印最大值及最小值
0.03414821649363875 0.9747800099794455


In [10]:
print("九、特別印法")
print(f"最小值：{x3}"f"最大值：{x4}")

九、特別印法
最小值：0.03414821649363875最大值：0.9747800099794455


In [11]:
print("隨機建立一個5x5列表(元素0-10之間)")
z = 10*np.random.random((5,5))
print (z)

隨機建立一個5x5列表(元素0-10之間)
[[4.14780418 3.12991513 9.63397776 6.47998805 1.97866096]
 [5.24711807 2.36952594 5.25617571 3.23007741 7.57039982]
 [7.83173554 5.97846321 8.50825183 6.67333084 7.23127182]
 [0.59020012 4.00731438 1.79322071 2.21703004 5.7957384 ]
 [6.71708636 2.31499873 6.82562031 5.18121093 4.79725817]]


In [12]:
print("九、列表最小最大值運算")
zmin,zmax = z.min(),z.max()
z = (z-zmin)/(zmax-zmin)                  
print (z)

九、列表最小最大值運算
[[0.39337589 0.28082457 1.         0.65125307 0.15352665]
 [0.51493061 0.19674586 0.51593214 0.29189984 0.77182345]
 [0.8007202  0.59579783 0.87552481 0.67263161 0.73432497]
 [0.         0.37784147 0.13302191 0.17988389 0.57559335]
 [0.6774698  0.19071661 0.68947075 0.50764304 0.46518813]]


In [13]:
print("建立一個5x5列表(元素都為0-4)")
o = np.zeros((5,5))
o += np.arange(5)
print (np.arange(5))
print (o)

建立一個5x5列表(元素都為0-4)
[0 1 2 3 4]
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [14]:
# #生成0~10之间均匀分布的11个数，包括0和10
#np.logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None)
                          #個數   #包含(stop)結束 #以多少為底數 #dtype : bool(布林值), int(整數), float(浮點數), complex(複數)
#numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
                #起點  #終點  #取樣數  #是否包含終點  #True 列印樣本距離 
print("十、從指定範圍內挑出樣本(樣本數自訂)，選擇是否包含起終點與是否列印樣本間隔")
z = np.linspace(0,10,4,endpoint=True,retstep=True)
print (z)

十、從指定範圍內挑出樣本(樣本數自訂)，選擇是否包含起終點與是否列印樣本間隔
(array([ 0.        ,  3.33333333,  6.66666667, 10.        ]), 3.3333333333333335)


In [15]:
print("十一、指定範圍分別列印出代入Log內運算")
e=np.logspace(0,2, num=2, endpoint=True, base=2, dtype=None)
print(e)

十一、指定範圍分別列印出代入Log內運算
[1. 4.]
