In [1]:
#安裝 Numpy 終端機輸入 "pip install numpy"
# 載入 Numpy 模組 設定別名 np
import numpy as np 

In [2]:
#開啟文本
# 自訂變數 = np.genfromtxt("檔名.txt", delimiter=",", dtype="U75", skip_header=1)
#delimiter=","表示每列的資料之間使用，做分隔符號
#dtype="U75"表示資料以字串方式置入（75為置入的字的個數)
#skip_header=1 ：表示從txt的第1列開始讀取(開頭為第零列)
txt = np.genfromtxt("world_alcohol.txt", delimiter=",", dtype="U75", skip_header=1) 

In [4]:
#會列印出 NaN (Not a Number)  無法表示 
print("一、印出文本內容(跳過第零列)")
print(txt)

一、印出文本內容(跳過第零列)
[['1986' 'Western Pacific' 'Viet Nam' 'Wine' '0']
 ['1986' 'Americas' 'Uruguay' 'Other' '0.5']
 ['1985' 'Africa' "Cte d'Ivoire" 'Wine' '1.62']
 ...
 ['1987' 'Africa' 'Malawi' 'Other' '0.75']
 ['1989' 'Americas' 'Bahamas' 'Wine' '1.5']
 ['1985' 'Africa' 'Malawi' 'Spirits' '0.31']]


In [6]:
print("二、印出檔案的類型")
print(type(txt))

二、印出檔案的類型
<class 'numpy.ndarray'>


In [7]:
#建立一個1x4的列表
vector = np.array([5, 10, 15, 20])
#建立一個3x3的列表 
matrix = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])
print ("三、列印剛剛所創1x4及3x3列表")
print (vector)
print (matrix)

三、列印剛剛所創1x4及3x3列表
[ 5 10 15 20]
[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


In [9]:
print("四、列印vector的列表形狀")
print(vector.shape)

四、列印vector的列表形狀
(4,)


In [10]:
print("五、列印vector的列表大小(元素個數)")
print(vector.size)

五、列印vector的列表大小(元素個數)
4


In [11]:
#建立一個2x3的列表          
matrix = np.array([[5, 10, 15], [20, 25, 30]])

print("六、列印matrix的列表形狀")
print(matrix.shape)

六、列印matrix的列表形狀
(2, 3)


In [12]:
print("七、列印matrix的列表大小(元素個數)")
print(matrix.size)

七、列印matrix的列表大小(元素個數)
6


In [13]:
#列表中每個元素必須為同類型 - 整數
numbers = np.array([1, 2, 3, 4])

print("八、列印出此列表元素的資料型態")
print(numbers.dtype)

八、列印出此列表元素的資料型態
int32


In [14]:
#列表中每個元素必須為同類型 - 浮點數(小數)
numbers = np.array([1.214, 2, 3, 4])
print("九、列印出此列表元素的資料型態")
print(numbers.dtype)

九、列印出此列表元素的資料型態
float64


In [15]:
#開頭皆為第0行第0列
#指定文本列表中 [1,4] 第二列第五行的元素 放進 x 變數
x = txt[1,4] 
#指定文本列表中 [2,2] 第三列第三行的元素 放進 y 變數
y = txt[2,2] 
print("十、列印出文本內列表位置[1,4][2,2]的元素")
print (x)
print (y)

十、列印出文本內列表位置[1,4][2,2]的元素
0.5
Cte d'Ivoire


In [16]:
# #創造一個1x4列表
# vector = np.array([5, 10, 15, 20])
#紙列印從第0個到第2個(不包含3)    印出5,10,15
print("十一、只列印vector列表中從第0個到第2個(不包含3)的元素")
print(vector[0:3]) 

十一、只列印vector列表中從第0個到第2個(不包含3)的元素
[ 5 10 15]


In [17]:
#創造一個3x3的列表 (二維)
matrix = np.array([
                    [5, 10, 15], 
                    [20, 25, 30],
                    [35, 40, 45]
                    ])
print("十二、列印第二行元素")                    
print(matrix[:,1]) 

十二、列印第二行元素
[10 25 40]


In [18]:
print("十三、列印每列的第零個元素到第一個元素")
print(matrix[:,0:2])

十三、列印每列的第零個元素到第一個元素
[[ 5 10]
 [20 25]
 [35 40]]


In [19]:
print("------------------------------")
print("Day1 結束")
print("------------------------------")

------------------------------
Day1 結束
------------------------------
