In [1]:
#載入 numpy 模組
import numpy as np
print("一、建立一個5x4列表(元素分別為sin0,sin1,...,sin19)")
data = np.sin(np.arange(20)).reshape(5,4)
print (data)

一、建立一個5x4列表(元素分別為sin0,sin1,...,sin19)
[[ 0.          0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155   0.6569866 ]
 [ 0.98935825  0.41211849 -0.54402111 -0.99999021]
 [-0.53657292  0.42016704  0.99060736  0.65028784]
 [-0.28790332 -0.96139749 -0.75098725  0.14987721]]


In [2]:
print("二、找出每行的最大值的【位置】")
ind = data.argmax(axis=0)
print (ind)

二、找出每行的最大值的【位置】
[2 0 3 1]


In [3]:
#Python3.0↑　xrange()包含在 range()
print("三、從range列表中選出最大值列印【以一維列表呈現】")
data_max = data[ind, range(data.shape[1])] 
print (data_max)

三、從range列表中選出最大值列印【以一維列表呈現】
[0.98935825 0.84147098 0.99060736 0.6569866 ]


In [4]:
print("四、比較兩邊的列表元素全相同則顯示True")
print(all(data_max == data.max(axis=0)))

四、比較兩邊的列表元素全相同則顯示True
True


In [5]:
print("五、比較兩邊的列表只要存在一個元素相等則顯示True")
print(any(data_max == data.max(axis=0)))

五、比較兩邊的列表只要存在一個元素相等則顯示True
True


In [6]:
print("六、arange(start,end(不含),等差10)")
a = np.arange(0, 40, 10)
print (a)

六、arange(start,end(不含),等差10)
[ 0 10 20 30]


In [7]:
print("七、建立3x5表格內容元素為a")
b = np.tile(a, (3, 5)) 
print (b)

七、建立3x5表格內容元素為a
[[ 0 10 20 30  0 10 20 30  0 10 20 30  0 10 20 30  0 10 20 30]
 [ 0 10 20 30  0 10 20 30  0 10 20 30  0 10 20 30  0 10 20 30]
 [ 0 10 20 30  0 10 20 30  0 10 20 30  0 10 20 30  0 10 20 30]]


In [8]:
print("八、建立1x4表格內容元素為a")
b = np.tile(a, (1, 4))
print (b)

八、建立1x4表格內容元素為a
[[ 0 10 20 30  0 10 20 30  0 10 20 30  0 10 20 30]]


In [9]:
print("建立一個2x3的列表")
a = np.array([[4, 3, 5], [1, 2, 1]])
print (a)

建立一個2x3的列表
[[4 3 5]
 [1 2 1]]


In [10]:
print("九、每一列由小到大做排序")
b = np.sort(a, axis=1)
print (b)

九、每一列由小到大做排序
[[3 4 5]
 [1 1 2]]


In [11]:
print("九、每一行由小到大做排序")
b = np.sort(a, axis=0)
print(b)

九、每一行由小到大做排序
[[1 2 1]
 [4 3 5]]


In [12]:
print("十、a列表,每一列由小到大做排序")
a.sort(axis=1)
print (a)

十、a列表,每一列由小到大做排序
[[3 4 5]
 [1 1 2]]


In [13]:
print("十一、判斷是否為同一個列表")
print (id(a))
print (id(b))

十一、判斷是否為同一個列表
2926816899312
2926816902192


In [14]:
print("建立1x4的列表")
a = np.array([4, 3, 1, 2])
print("十二、argsort 將列表由小到大的【位置】做排序")
j = np.argsort(a)
print (j)

建立1x4的列表
十二、argsort 將列表由小到大的【位置】做排序
[2 3 1 0]


In [15]:
print("十三、將列印a列表中[位置]，【由小到大】")
print (a[j])

十三、將列印a列表中[位置]，【由小到大】
[1 2 3 4]
