In [1]:
import numpy as np
#創造5x5矩陣(元素為0-24)
a = np.arange(25).reshape(5,5)
print (a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [4]:
print("一、列交換(第零列與第四列)")
#a[[0,4]] = a[[4,0]] 也行，預設為列
a[[4,0]] = a[[0,4]]
print (a)

一、列交換(第零列與第四列)
[[20 21 22 23 24]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [ 0  1  2  3  4]]


In [7]:
print("二、行交換(第零行與第一行)")
a[:,[0,1]] = a[:,[1,0]]
print(a)

二、行交換(第零行與第一行)
[[21 20 22 23 24]
 [ 6  5  7  8  9]
 [11 10 12 13 14]
 [16 15 17 18 19]
 [ 1  0  2  3  4]]


In [8]:
#找出數列中最接近的數
z = np.array([[0,1,2,3],[4,5,6,7]])
a = 5.1
#abs, fabs 計算整數、浮點數或複數的絕對值。對於非複數值，可以使用更快的fabs。
#np.abs(z-a).argmin()   z為陣列，a為數，找出陣列中與給定值最接近的數，利用陣列進行資料處理 數學和統計方法
#argmin() 分別為最小值的索引
#argmax() 分別為最大值的索引
print("三、找出最接近的數，abs找出差距最小，argmin找最小的位置")
print (np.abs(z-a).argmin())

三、找出最接近的數，abs找出差距最小，argmin找最小的位置
5


In [11]:
#判斷矩陣是否有每列or每行為0
print("建立一個2x10列表(元素值為0-2之間)")
z = np.random.randint(0,3,(2,10))
print (z)

建立一個2x10列表(元素值為0-2之間)
[[1 2 0 1 1 0 1 2 2 1]
 [2 0 0 0 0 1 1 2 0 1]]


In [10]:
print("四、判斷每一行是否為零")
print (z.any(axis=0))

四、判斷每一行是否為零
[ True  True  True False  True  True  True  True False  True]


In [12]:
print("五、判斷每一行是否為非零")
print (z.all(axis=0))

五、判斷每一行是否為非零
[ True False False False False False  True  True False  True]


In [13]:
print("六、指令的介紹")
print(help(np.random.randint))

六、指令的介紹
Help on built-in function randint:

randint(...) method of numpy.random.mtrand.RandomState instance
    randint(low, high=None, size=None, dtype=int)
    
    Return random integers from `low` (inclusive) to `high` (exclusive).
    
    Return random integers from the "discrete uniform" distribution of
    the specified dtype in the "half-open" interval [`low`, `high`). If
    `high` is None (the default), then results are from [0, `low`).
    
    .. note::
        New code should use the ``integers`` method of a ``default_rng()``
        instance instead; please see the :ref:`random-quick-start`.
    
    Parameters
    ----------
    low : int or array-like of ints
        Lowest (signed) integers to be drawn from the distribution (unless
        ``high=None``, in which case this parameter is one above the
        *highest* such integer).
    high : int or array-like of ints, optional
        If provided, one above the largest (signed) integer to be drawn
        from the di

In [14]:
#np.linspace(star,end,均勻取numble)
print("七、一定的範圍內均勻取樣本數")
x=np.linspace(-1,1,3)
print(x)
y=np.linspace(2,4,2)
print(y)

七、一定的範圍內均勻取樣本數
[-1.  0.  1.]
[2. 4.]


In [16]:
print("代研究")  
#np.meshgrid (以為中心) ;(x,y)二維;(x,y,z)三維 
x,y = np.meshgrid(np.linspace(-1,1,3),np.linspace(2,4,2))
print (x)
print (y)
z=np.meshgrid(3,2)
print(z)

代研究
[[-1.  0.  1.]
 [-1.  0.  1.]]
[[2. 2. 2.]
 [4. 4. 4.]]
[array([[3]]), array([[2]])]


In [19]:
print(help(np.meshgrid))

Help on function meshgrid in module numpy:

meshgrid(*xi, copy=True, sparse=False, indexing='xy')
    Return coordinate matrices from coordinate vectors.
    
    Make N-D coordinate arrays for vectorized evaluations of
    N-D scalar/vector fields over N-D grids, given
    one-dimensional coordinate arrays x1, x2,..., xn.
    
    .. versionchanged:: 1.9
       1-D and 0-D cases are allowed.
    
    Parameters
    ----------
    x1, x2,..., xn : array_like
        1-D arrays representing the coordinates of a grid.
    indexing : {'xy', 'ij'}, optional
        Cartesian ('xy', default) or matrix ('ij') indexing of output.
        See Notes for more details.
    
        .. versionadded:: 1.7.0
    sparse : bool, optional
        If True a sparse grid is returned in order to conserve memory.
        Default is False.
    
        .. versionadded:: 1.7.0
    copy : bool, optional
        If False, a view into the original arrays are returned in order to
        conserve memory.  Default

In [20]:
print("八、畢氏定理")
D = np.sqrt(x**2+y**2)
print (D)
sigma,mu = 1,0
a = np.exp(-(D-mu)**2/(2*sigma**2))
print (a)

八、畢氏定理
[[2.23606798 2.         2.23606798]
 [4.12310563 4.         4.12310563]]
[[0.082085   0.13533528 0.082085  ]
 [0.00020347 0.00033546 0.00020347]]
