In [1]:
#載入 numpy 模組
import numpy as np

In [2]:
#創造一個列表元素個數為0~14 (15個) 矩陣形狀為3x5
a = np.arange(15).reshape(3, 5)
print("一、創造一個列表元素個數為0~14 (15個) 矩陣形狀為3x5")
print(a)

一、創造一個列表元素個數為0~14 (15個) 矩陣形狀為3x5
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [3]:
#矩陣形狀
print("二、印出列表的形狀")
print(a.shape)

二、印出列表的形狀
(3, 5)


In [4]:
#矩陣維度
print("三、列印出列表的維度")
print(a.ndim)

三、列印出列表的維度
2


In [5]:
print("四、列印列表資料型態")
print (a.dtype)

四、列印列表資料型態
int32


In [6]:
print("五、列印列表的大小(元素個數)")
print (a.size)

五、列印列表的大小(元素個數)
15


In [7]:
print("六、建立一個3x4的零矩陣")
b = np.zeros ((3,4))
print(b)

六、建立一個3x4的零矩陣
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [8]:
print("七、建立一個2x3x4矩陣(3維)元素全是1")
c=np.ones((2,3,4), dtype=np.int32 )
print(c)

七、建立一個2x3x4矩陣(3維)元素全是1
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


In [9]:
#numpy.arange(star,stop,step,dtype) 
print("八、使用range建立列表(類等差數列)")
e=np.arange( 10, 30, 5 )
print(e)

八、使用range建立列表(類等差數列)
[10 15 20 25]


In [10]:
print("九、range進階使用")
f=np.arange( 0, 2, 0.3 )
print(f)

九、range進階使用
[0.  0.3 0.6 0.9 1.2 1.5 1.8]


In [11]:
print("十、建立一個具12個元素之列表(4x3)")
g=np.arange(12).reshape(4,3)
print (g)

十、建立一個具12個元素之列表(4x3)
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [12]:
# np 模組中使用 pi  (np.pi)
#from numpy import pi 指令將np.pi 簡化為 pi
from numpy import pi
print("十一、建立一個等差級數的列表(從0開始)，2*pi 為等差，算100個")
h = np.linspace( 0, 2*pi, 100 )
print(h)

十一、建立一個等差級數的列表(從0開始)，2*pi 為等差，算100個
[0.         0.06346652 0.12693304 0.19039955 0.25386607 0.31733259
 0.38079911 0.44426563 0.50773215 0.57119866 0.63466518 0.6981317
 0.76159822 0.82506474 0.88853126 0.95199777 1.01546429 1.07893081
 1.14239733 1.20586385 1.26933037 1.33279688 1.3962634  1.45972992
 1.52319644 1.58666296 1.65012947 1.71359599 1.77706251 1.84052903
 1.90399555 1.96746207 2.03092858 2.0943951  2.15786162 2.22132814
 2.28479466 2.34826118 2.41172769 2.47519421 2.53866073 2.60212725
 2.66559377 2.72906028 2.7925268  2.85599332 2.91945984 2.98292636
 3.04639288 3.10985939 3.17332591 3.23679243 3.30025895 3.36372547
 3.42719199 3.4906585  3.55412502 3.61759154 3.68105806 3.74452458
 3.8079911  3.87145761 3.93492413 3.99839065 4.06185717 4.12532369
 4.1887902  4.25225672 4.31572324 4.37918976 4.44265628 4.5061228
 4.56958931 4.63305583 4.69652235 4.75998887 4.82345539 4.88692191
 4.95038842 5.01385494 5.07732146 5.14078798 5.2042545  5.26772102
 5.33118753 5.39465405 5.458

In [13]:
print("十二、取三角函數")
i=np.sin(np.linspace( 0, 2*pi, 100 ))
print(i)

十二、取三角函數
[ 0.00000000e+00  6.34239197e-02  1.26592454e-01  1.89251244e-01
  2.51147987e-01  3.12033446e-01  3.71662456e-01  4.29794912e-01
  4.86196736e-01  5.40640817e-01  5.92907929e-01  6.42787610e-01
  6.90079011e-01  7.34591709e-01  7.76146464e-01  8.14575952e-01
  8.49725430e-01  8.81453363e-01  9.09631995e-01  9.34147860e-01
  9.54902241e-01  9.71811568e-01  9.84807753e-01  9.93838464e-01
  9.98867339e-01  9.99874128e-01  9.96854776e-01  9.89821442e-01
  9.78802446e-01  9.63842159e-01  9.45000819e-01  9.22354294e-01
  8.95993774e-01  8.66025404e-01  8.32569855e-01  7.95761841e-01
  7.55749574e-01  7.12694171e-01  6.66769001e-01  6.18158986e-01
  5.67059864e-01  5.13677392e-01  4.58226522e-01  4.00930535e-01
  3.42020143e-01  2.81732557e-01  2.20310533e-01  1.58001396e-01
  9.50560433e-02  3.17279335e-02 -3.17279335e-02 -9.50560433e-02
 -1.58001396e-01 -2.20310533e-01 -2.81732557e-01 -3.42020143e-01
 -4.00930535e-01 -4.58226522e-01 -5.13677392e-01 -5.67059864e-01
 -6.18158986e-01

In [14]:
print("十三、取三角函數")
j=np.sin(pi/6)
k=np.cos(pi/3)
print(j)
print(k)

十三、取三角函數
0.49999999999999994
0.5000000000000001


In [15]:
a = np.array( [20,30,40,50] )
b = np.arange( 4 )
print("十四、創建兩個1x4列表")
print (a) 
print (b)

十四、創建兩個1x4列表
[20 30 40 50]
[0 1 2 3]


In [16]:
c = a-b
d = a+b 
print("十五、列表運算")
print (c)
print (d)

十五、列表運算
[20 29 38 47]
[20 31 42 53]


In [17]:
print("十六、平方運算")
print (b**2)

十六、平方運算
[0 1 4 9]


In [18]:
print("十七、比較運算")
print (a<35)

十七、比較運算
[ True  True False False]


In [19]:
#建立兩個2x2矩陣
A = np.array( [[1,1],
               [0,1]] )
B = np.array( [[2,0],
               [3,4]] )
print (A)
print (B)

[[1 1]
 [0 1]]
[[2 0]
 [3 4]]


In [21]:
#print A*B
print("十八、矩陣乘積(3種指令)")
print (A.dot(B))
print("\n")
print (np.dot(A, B))
print("\n") 
print (A@B)

十八、矩陣乘積(3種指令)
[[5 4]
 [3 4]]


[[5 4]
 [3 4]]


[[5 4]
 [3 4]]


In [22]:
print("------------------------------")
print("Day3 結束")
print("------------------------------")

------------------------------
Day3 結束
------------------------------
